package com.bytecoder.vplay.backend.data.database

import androidx.room.*
import androidx.lifecycle.LiveData

@Dao
interface WatchHistoryDao {
    @Query("SELECT * FROM watch_history ORDER BY lastWatched DESC")
    fun getAllHistory(): LiveData<List<WatchHistoryEntry>>

    @Query("SELECT * FROM watch_history WHERE isVideo = :isVideo ORDER BY lastWatched DESC LIMIT :limit")
    fun getRecentHistory(isVideo: Boolean, limit: Int = 20): LiveData<List<WatchHistoryEntry>>

    @Query("SELECT * FROM watch_history ORDER BY watchCount DESC, lastWatched DESC LIMIT :limit")
    fun getMostWatched(limit: Int = 20): LiveData<List<WatchHistoryEntry>>

    @Query("SELECT * FROM watch_history WHERE mediaId = :mediaId")
    suspend fun getHistoryEntry(mediaId: String): WatchHistoryEntry?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertOrUpdate(entry: WatchHistoryEntry)

    @Query("UPDATE watch_history SET lastPosition = :position WHERE mediaId = :mediaId")
    suspend fun updatePosition(mediaId: String, position: Long)

    @Query("UPDATE watch_history SET watchCount = watchCount + 1, lastWatched = :timestamp WHERE mediaId = :mediaId")
    suspend fun incrementWatchCount(mediaId: String, timestamp: Long = System.currentTimeMillis())

    @Query("DELETE FROM watch_history WHERE mediaId = :mediaId")
    suspend fun deleteEntry(mediaId: String)

    @Query("DELETE FROM watch_history")
    suspend fun clearHistory()
}

@Dao
interface PlaylistDao {
    @Query("SELECT * FROM playlists ORDER BY modified DESC")
    fun getAllPlaylists(): LiveData<List<Playlist>>

    @Query("SELECT * FROM playlists WHERE isAutoGenerated = 0 ORDER BY name ASC")
    fun getUserPlaylists(): LiveData<List<Playlist>>

    @Query("SELECT * FROM playlists WHERE isAutoGenerated = 1")
    fun getAutoPlaylists(): LiveData<List<Playlist>>

    @Query("SELECT * FROM playlists WHERE id = :id")
    suspend fun getPlaylist(id: Long): Playlist?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylist(playlist: Playlist): Long

    @Update
    suspend fun updatePlaylist(playlist: Playlist)

    @Delete
    suspend fun deletePlaylist(playlist: Playlist)

    @Query("SELECT * FROM playlist_items WHERE playlistId = :playlistId ORDER BY position ASC")
    fun getPlaylistItems(playlistId: Long): LiveData<List<PlaylistItem>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylistItem(item: PlaylistItem)

    @Query("DELETE FROM playlist_items WHERE playlistId = :playlistId AND mediaId = :mediaId")
    suspend fun removePlaylistItem(playlistId: Long, mediaId: String)

    @Query("DELETE FROM playlist_items WHERE playlistId = :playlistId")
    suspend fun clearPlaylist(playlistId: Long)

    @Query("UPDATE playlist_items SET position = :newPosition WHERE id = :itemId")
    suspend fun updateItemPosition(itemId: Long, newPosition: Int)
}

@Dao
interface DownloadDao {
    @Query("SELECT * FROM downloads ORDER BY startTime DESC")
    fun getAllDownloads(): LiveData<List<DownloadEntry>>

    @Query("SELECT * FROM downloads WHERE status = :status ORDER BY startTime DESC")
    fun getDownloadsByStatus(status: String): LiveData<List<DownloadEntry>>

    @Query("SELECT * FROM downloads WHERE status = 'completed' ORDER BY completedTime DESC")
    fun getCompletedDownloads(): LiveData<List<DownloadEntry>>

    @Query("SELECT * FROM downloads WHERE id = :id")
    suspend fun getDownload(id: String): DownloadEntry?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertDownload(download: DownloadEntry)

    @Update
    suspend fun updateDownload(download: DownloadEntry)

    @Query("UPDATE downloads SET status = :status, progress = :progress, downloadedBytes = :downloadedBytes WHERE id = :id")
    suspend fun updateProgress(id: String, status: String, progress: Float, downloadedBytes: Long)

    @Query("UPDATE downloads SET status = 'completed', progress = 1.0, completedTime = :completedTime, localPath = :localPath WHERE id = :id")
    suspend fun markCompleted(id: String, localPath: String, completedTime: Long = System.currentTimeMillis())

    @Query("UPDATE downloads SET status = 'failed', error = :error WHERE id = :id")
    suspend fun markFailed(id: String, error: String)

    @Delete
    suspend fun deleteDownload(download: DownloadEntry)

    @Query("DELETE FROM downloads WHERE status = 'completed' AND completedTime < :before")
    suspend fun deleteOldCompletedDownloads(before: Long)
}

@Dao
interface AnalyticsDao {
    @Insert
    suspend fun insertAnalytics(entry: AnalyticsEntry)

    @Query("SELECT COUNT(*) FROM analytics WHERE mediaId = :mediaId AND action = 'play'")
    suspend fun getPlayCount(mediaId: String): Int

    @Query("SELECT SUM(duration) FROM analytics WHERE mediaId = :mediaId AND action = 'play'")
    suspend fun getTotalPlayTime(mediaId: String): Long

    @Query("SELECT mediaId, COUNT(*) as playCount FROM analytics WHERE action = 'play' GROUP BY mediaId ORDER BY playCount DESC LIMIT :limit")
    suspend fun getMostPlayedMedia(limit: Int = 20): List<MediaPlayStats>

    @Query("DELETE FROM analytics WHERE timestamp < :before")
    suspend fun deleteOldAnalytics(before: Long)

    @Query("SELECT action, COUNT(*) as count FROM analytics WHERE timestamp > :since GROUP BY action")
    suspend fun getActionStats(since: Long): List<ActionStats>
}

data class MediaPlayStats(
    val mediaId: String,
    val playCount: Int
)

data class ActionStats(
    val action: String,
    val count: Int
)

@Dao
interface BookmarkDao {
    @Query("SELECT * FROM bookmarks ORDER BY lastUsed DESC")
    fun getAllBookmarks(): LiveData<List<BookmarkEntry>>

    @Query("SELECT * FROM bookmarks WHERE category = :category ORDER BY lastUsed DESC")
    fun getBookmarksByCategory(category: String): LiveData<List<BookmarkEntry>>

    @Query("SELECT DISTINCT category FROM bookmarks ORDER BY category ASC")
    fun getCategories(): LiveData<List<String>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertBookmark(bookmark: BookmarkEntry)

    @Update
    suspend fun updateBookmark(bookmark: BookmarkEntry)

    @Delete
    suspend fun deleteBookmark(bookmark: BookmarkEntry)

    @Query("UPDATE bookmarks SET lastUsed = :timestamp, useCount = useCount + 1 WHERE url = :url")
    suspend fun markUsed(url: String, timestamp: Long = System.currentTimeMillis())
}

@Dao
interface FileMetadataDao {
    @Query("SELECT * FROM file_metadata WHERE path = :path")
    suspend fun getMetadata(path: String): FileMetadata?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertMetadata(metadata: FileMetadata)

    @Query("SELECT * FROM file_metadata WHERE mimeType LIKE 'video/%' ORDER BY lastModified DESC")
    fun getAllVideoMetadata(): LiveData<List<FileMetadata>>

    @Query("SELECT * FROM file_metadata WHERE mimeType LIKE 'audio/%' ORDER BY lastModified DESC")
    fun getAllAudioMetadata(): LiveData<List<FileMetadata>>

    @Query("SELECT DISTINCT artist FROM file_metadata WHERE artist IS NOT NULL AND artist != '' ORDER BY artist ASC")
    fun getAllArtists(): LiveData<List<String>>

    @Query("SELECT DISTINCT album FROM file_metadata WHERE album IS NOT NULL AND album != '' ORDER BY album ASC")
    fun getAllAlbums(): LiveData<List<String>>

    @Query("SELECT DISTINCT genre FROM file_metadata WHERE genre IS NOT NULL AND genre != '' ORDER BY genre ASC")
    fun getAllGenres(): LiveData<List<String>>

    @Query("SELECT * FROM file_metadata WHERE artist = :artist ORDER BY album ASC, track ASC")
    fun getFilesByArtist(artist: String): LiveData<List<FileMetadata>>

    @Query("SELECT * FROM file_metadata WHERE album = :album ORDER BY track ASC")
    fun getFilesByAlbum(album: String): LiveData<List<FileMetadata>>

    @Query("SELECT * FROM file_metadata WHERE genre = :genre ORDER BY artist ASC, album ASC")
    fun getFilesByGenre(genre: String): LiveData<List<FileMetadata>>

    @Query("DELETE FROM file_metadata WHERE analyzedAt < :before")
    suspend fun deleteOldMetadata(before: Long)
}


