package com.bytecoder.vplay.backend.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "watch_history")
data class WatchHistoryEntry(
    @PrimaryKey val mediaId: String,
    val title: String,
    val uri: String,
    val isVideo: Boolean,
    val lastPosition: Long = 0,
    val duration: Long = 0,
    val lastWatched: Long = System.currentTimeMillis(),
    val watchCount: Int = 1,
    val thumbnail: String? = null,
    val subtitle: String? = null
)

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val description: String = "",
    val coverArt: String? = null,
    val created: Long = System.currentTimeMillis(),
    val modified: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false,
    val autoGenerationType: String? = null, // "recent", "most_played", "favorites", etc.
    val tags: String = "" // CSV of tags
)

@Entity(tableName = "playlist_items")
data class PlaylistItem(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val playlistId: Long,
    val mediaId: String,
    val title: String,
    val uri: String,
    val isVideo: Boolean,
    val position: Int,
    val addedAt: Long = System.currentTimeMillis(),
    val thumbnail: String? = null,
    val subtitle: String? = null,
    val duration: Long = 0
)

@Entity(tableName = "downloads")
data class DownloadEntry(
    @PrimaryKey val id: String,
    val url: String,
    val title: String,
    val localPath: String? = null,
    val status: String, // "pending", "downloading", "completed", "failed", "paused"
    val progress: Float = 0f,
    val totalBytes: Long = 0,
    val downloadedBytes: Long = 0,
    val startTime: Long = System.currentTimeMillis(),
    val completedTime: Long? = null,
    val error: String? = null,
    val quality: String? = null,
    val isVideo: Boolean = true,
    val thumbnail: String? = null
)

@Entity(tableName = "analytics")
data class AnalyticsEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val mediaId: String,
    val action: String, // "play", "pause", "seek", "complete", "skip"
    val timestamp: Long = System.currentTimeMillis(),
    val sessionId: String,
    val duration: Long = 0, // how long the action lasted
    val position: Long = 0, // position in media when action occurred
    val metadata: String = "" // JSON for additional data
)

@Entity(tableName = "bookmarks")
data class BookmarkEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val url: String,
    val title: String? = null,
    val category: String = "general",
    val added: Long = System.currentTimeMillis(),
    val lastUsed: Long = System.currentTimeMillis(),
    val useCount: Int = 1
)

@Entity(tableName = "file_metadata")
data class FileMetadata(
    @PrimaryKey val path: String,
    val name: String,
    val size: Long,
    val lastModified: Long,
    val mimeType: String? = null,
    val duration: Long = 0,
    val width: Int = 0,
    val height: Int = 0,
    val bitrate: Int = 0,
    val artist: String? = null,
    val album: String? = null,
    val genre: String? = null,
    val year: Int = 0,
    val track: Int = 0,
    val albumArt: String? = null,
    val lyrics: String? = null,
    val chapters: String? = null, // JSON array of chapters
    val audioTracks: String? = null, // JSON array of audio tracks
    val subtitleTracks: String? = null, // JSON array of subtitle tracks
    val analyzedAt: Long = System.currentTimeMillis()
)


